### ISSUE TITLE
Issues with errors

### ISSUE THREAD

**Issue by a327ex** [morew4rd/lyte2d#3]
Decided to try using your framework to see how far along it was and came across a few issues:

1. Errors only show the error line but no stack traceback to see where the error came from, this makes finding out what's wrong significantly more difficult.

2. Errors only output to console and the game window closes immediately. This forces you to run the game from an already open console window, otherwise you won't be able to see what the error was, as any console window opened from running the game from a command (i.e. I normally run it from a run.bat file) also closes when the main game window closes. LÖVE shows the error on screen and doesn't close the game's window, so you can still see what's sent to the console (on top of seeing the error + stack traceback on screen). GameMaker closes the window but opens a new one that shows you the stack traceback I think.

Hope you don't mind me creating a few issues over the next few days as I try making something with your framework.

**Comment by morew4rd** [comment]
Thank you for filing this!  I should fix (1) in 0.5. 

I'm thinking about how to approach (2). Do you like love2d's style here more or gamemaker's? Or something else altogether? 

And filing other bugs... Please do! Any feedback at all is appreciated! (Including non-bug/API feedback/usability/etc.)

**Comment by a327ex** [comment]
I think LÖVE's way is best, especially because it allows you to do whatever you want with the error string, like send it to your server from the client. However you should probably do what's easiest and will take less effort first, since this is a less important issue compared to the first.

**Comment by morew4rd** [comment]
Made a (temporary) fix for (1) and got an official built out: https://github.com/morew4rd/lyte2d/releases/tag/v0.5-pre.2

For now, I just copied lua interpreter's way of doing this. I'm refactoring/unprototyping that part of the code (entry point, loaders, etc.) so there'll be probably some changes there before 0.5.

Hope this helps with the rest of your exploration!

**Comment by morew4rd** [comment]
(2) is for the most part fixed. I have a "prerelease" with it here: https://github.com/morew4rd/lyte2d/releases/tag/v0.6-pre.7 Will be "officially" released with 0.6.  (Meaning getting more testing.)

The only issue that I'm aware of now is that `draw_text` API currently does not handle escape characters such as newlines so long error messages look weird. But probably not a very big deal for now.

It's ugly, but hopefully functional.

**Comment by morew4rd** [comment]
Closing this as fixed in 0.6 release (Fixed in 0.6 (https://github.com/morew4rd/lyte2d/releases/tag/v0.6))

There are more error classes to be added that are visible in the window, but at least for now the window doesn't close, shows most code errors on the window.

Please file another one/reopen if there are other issues around this.
